[book]
authors = [ "Optimism Contributors",]
language = "en"
multilingual = false
src = "src"
title = "OP Stack Devdocs"

[build]
create-missing = false

[output.html]
google-analytics = "G-YNLYYEX7MN"
